services:
  # eliza-chat:
  #   platform: linux/amd64
  #   build:
  #     context: ./eliza-chat
  #     dockerfile: Dockerfile
  #   image: ghcr.io/andrearettaroli/ethdam:latest
  #   environment:
  #     - OPENAI_API_KEY=${OPENAI_API_KEY}
  #     - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
  #     - DATABASE_URL=${DATABASE_URL}
  #   ports:
  #     - "3000:3000"
  #     - "5173:5173"
  #   depends_on:
  #     - eliza-database

  # eliza-database:
  #   image: ankane/pgvector
  #   container_name: eliza-database
  #   environment:
  #     - POSTGRES_DB=${POSTGRES_DB}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #   ports:
  #     - "5000:5432"
  #   # volumes:
  #   #   - db-data:/var/lib/postgresql/data
  #   restart: always
  server:
    build:
      context: ./server-hono
    expose:
      - 4021
    restart: unless-stopped
  mcp:
    build:
      context: ./mcp
    environment:
      - NODE_ENV=production
      - PORT=${MCP_PORT:-4000}
    expose:
      - "${MCP_PORT:-4000}"
    restart: unless-stopped
    depends_on:
      - server
    

  bot:
    build:
      context: .
    command: python telegram_mcp_bot.py
    environment:
      - TOKEN=${TOKEN}
      - MCP_HOST=mcp
      - MCP_PORT=${MCP_PORT:-4000}
    depends_on:
      - mcp